### ISSUE TITLE
Skeletron Prime Bugged

### ISSUE THREAD

**Issue by KiberZero** [hocha113/CalamityOverhaul#11] opened 2024-06-02 19:38 UTC
In general. I once decided to take down skeletron prime and then I noticed that his head looks different, namely straight from the Master mode, even though I am currently playing in the Expert + Revergence combination (although I myself am in the Master + Death didn't play, so I could be wrong). And after I stripped his hands, I noticed that some attack patterns were missing.
![Скриншот 02-06-2024 204451](https://github.com/hocha113/CalamityOverhaul/assets/72599376/4bb50c52-b22c-4a26-b39b-b2fc26b431e2)

P.S. I have already applied the Calamity discord server and after a short discussion it was decided that the problem was in Cal overhaul.

**Comment by YSKNM** [comment] 2024-06-02 21:46
There's also more to the bug as well, if you're on Death-Master, Skeletron prime only has one head, and doesn't summon the other mech bosses later in the fight, definitely doesn't behave as intended 


Skeletron Prime had new behavior in 2.0.4 (behavior being him having two head and summoning the other mechanical bosses), and Calamity overhaul seems to break it. This also links to the first part of the bug report, where Skeletron Prime's head used a different sprite, which may be a side effect from the bug

**Comment by KiberZero** [comment] 2024-06-02 22:36
Well, in that case, I'll wait patiently for the patch, hoping that I won't stumble into more pressing problems.

Thank you for the detailed answer.

**Comment by hocha113** [comment] 2024-06-03 08:17
I know, this issue comes from an unfinished AI modification. It will be fixed

**Closed** 2024-06-21 14:42 UTC
